<?php echo $this->pageTitle(sprintf($this->translate('Search results for “%s”'), $query)); ?>
<div>
    <?php 
    $site = $this->layout()->site;
     $fulltextQuery = $this->params()->fromQuery('fulltext_search');
        $queryLimit = [
            'fulltext_search' => $fulltextQuery,
            'site_id' => $site->id(),
            'limit' => 10,
        ];
        $itemSetsResponse = $this->api()->search('item_sets', $queryLimit);
        $itemSets = $itemSetsResponse->getContent();
        $itemSetsTotal = $itemSetsResponse->getTotalResults();
     ?>
    <h2><?php echo $this->translate('Reports'); ?></h2>
    <?php if ($itemSets): ?>
    <ul>
        <?php foreach ($itemSets as $itemSet): ?>
        <li><a href="<?php echo $itemSet->url(); ?>?sort_by=numeric:timestamp:7&sort_order=asc"><?php echo $itemSet->displayTitle(); ?></a></li>
        <?php endforeach; ?>
    </ul>
    <?php echo $this->hyperlink(
        sprintf($this->translate('View all results (%s total)'), $itemSetsTotal),
        $this->url(
            'site/resource',
            ['controller' => 'item-set', 'action' => 'browse'],
            ['query' => ['fulltext_search' => $query]],
            true
        )
    ); ?>
    <?php else: ?>
    <p><?php echo $this->translate('No reports found'); ?></p>
    <?php endif; ?>
</div>
<div>
    <h2><?php echo $this->translate('Primary Sources'); ?></h2>
    <?php if ($items): ?>
    <ul>
        <?php foreach ($items as $item): ?>
        <li><?php echo $item->link($item->displayTitle()); ?></li>
        <?php endforeach; ?>
    </ul>
    <?php echo $this->hyperlink(
        sprintf($this->translate('View all results (%s total)'), $itemsTotal),
        $this->url(
            'site/resource',
            ['controller' => 'item', 'action' => 'browse'],
            ['query' => ['fulltext_search' => $query]],
            true
        )
    ); ?>
    <?php else: ?>
    <p><?php echo $this->translate('No primary sources found'); ?></p>
    <?php endif; ?>
</div>