<?php
$id = $page->title();
$this->htmlElement('body')->appendAttribute('class', 'page');
$this->htmlElement('body')->appendAttribute('id', $id);
$this->pageTitle($page->title(), 2);
$showPagePagination = $this->siteSetting('show_page_pagination', true);
?>


<?php $this->trigger('view.show.before'); ?>
<div class="blocks cell">
    <?php echo $this->content; ?>
</div>
<?php $this->trigger('view.show.after'); ?>

